export const  GET_FARMERS_REQUEST = "GET_FARMERS_REQUEST";
export const  GET_FARMERS_SUCCESS = "GET_FARMERS_SUCCESS";
export const  GET_FARMERS_FAIL = "GET_FARMERS_FAIL";

export const GET_FARMERS_BY_FARM_REQUEST = "GET_FARMERS_BY_FARM_REQUEST";
export const GET_FARMERS_BY_FARM_SUCCESS = "GET_FARMERS_BY_FARM_SUCCESS";
export const GET_FARMERS_BY_FARM_FAIL = "GET_FARMERS_BY_FARM_FAIL";

export const GET_FARMERS_TOTAL_REQUEST = "GET_FARMERS_TOTAL_REQUEST";
export const GET_FARMERS_TOTAL_SUCCESS = "GET_FARMERS_TOTAL_SUCCESS";
export const GET_FARMERS_TOTAL_FAIL = "GET_FARMERS_TOTAL_FAIL";

export const GET_FARMER_REQUEST = "GET_FARMER_REQUEST";
export const GET_FARMER_SUCCESS = "GET_FARMER_SUCCESS";
export const GET_FARMER_FAIL = "GET_FARMER_FAIL";