export const  ADD_FARMS_REQUEST = "ADD_FARMS_REQUEST";
export const  ADD_FARMS_SUCCESS = "ADD_FARMS_SUCCESS";
export const  ADD_FARMS_FAIL = "ADD_FARMS_FAIL";

export const  GET_FARMS_REQUEST = "GET_FARMS_REQUEST";
export const  GET_FARMS_SUCCESS = "GET_FARMS_SUCCESS";
export const  GET_FARMS_FAIL = "GET_FARMS_FAIL";

export const GET_FARM_REQUEST = "GET_FARM_REQUEST";
export const GET_FARM_SUCCESS = "GET_FARM_SUCCESS";
export const GET_FARM_FAIL = "GET_FARM_FAIL";